import type { ExperienceTaste } from "../../types/taste";

export const EXPERIENCE_TASTES: ExperienceTaste[] = [
  {
    id: "sunrise",
    slug: "sunrise",
    name: "Sunrise & Dawn Light",
    description: "Quiet first-light vantage points before the world stirs",
    icon: "🌅",
    compatibleTravelTastes: ["mountains", "beaches", "sunrise_sunset", "photography", "nature"],
  },
  {
    id: "sunset",
    slug: "sunset",
    name: "Sunset Horizons & Twilight",
    description: "Golden hour glows, dusk panoramas & twilight reflections",
    icon: "🌇",
    compatibleTravelTastes: ["beaches", "mountains", "sunrise_sunset", "photography", "historical"],
  },
  {
    id: "peaceful",
    slug: "peaceful",
    name: "Quiet Solitude & Peace",
    description: "Serene sanctuaries away from loudspeakers, traffic & urban noise",
    icon: "🕊️",
    compatibleTravelTastes: [
      "mountains",
      "nature",
      "beaches",
      "spiritual",
      "local_life",
      "sunrise_sunset",
    ],
  },
  {
    id: "less_crowded",
    slug: "less_crowded",
    name: "Less Crowded & Offbeat",
    description: "Lesser-known alternatives to commercial tour-bus itineraries",
    icon: "🧭",
    compatibleTravelTastes: [
      "mountains",
      "nature",
      "historical",
      "beaches",
      "local_life",
      "spiritual",
      "culture_art",
    ],
  },
  {
    id: "photography",
    slug: "photography",
    name: "Photography Frames",
    description: "Dramatic textures, symmetry, atmospheric shadows & rich vistas",
    icon: "📸",
    compatibleTravelTastes: [
      "mountains",
      "nature",
      "photography",
      "historical",
      "beaches",
      "sunrise_sunset",
      "culture_art",
    ],
  },
  {
    id: "adventure",
    slug: "adventure",
    name: "Adrenaline & Tough Trails",
    description: "Challenging terrain, steep ascents & backcountry exploration",
    icon: "⛰️",
    compatibleTravelTastes: ["mountains", "adventure", "nature"],
  },
  {
    id: "wildlife_spotting",
    slug: "wildlife_spotting",
    name: "Wildlife & Native Fauna",
    description: "Natural habitats of rare birds, mammals & marine life",
    icon: "🦅",
    compatibleTravelTastes: ["nature", "adventure", "beaches"],
  },
  {
    id: "forest_trails",
    slug: "forest_trails",
    name: "Forest Trails & Canopy",
    description: "Mossy footpaths through old-growth trees & sacred groves",
    icon: "🌲",
    compatibleTravelTastes: ["nature", "mountains", "adventure"],
  },
  {
    id: "ancient_ruins",
    slug: "ancient_ruins",
    name: "Ancient Ruins & Carvings",
    description: "Stone inscriptions, dilapidated fortresses & archaeological lore",
    icon: "🏺",
    compatibleTravelTastes: ["historical", "culture_art", "spiritual"],
  },
  {
    id: "architectural_detail",
    slug: "architectural_detail",
    name: "Architectural Geometry",
    description: "Intricate stepwells, domes, carved pillars & heritage facades",
    icon: "📐",
    compatibleTravelTastes: ["historical", "spiritual", "photography", "culture_art"],
  },
  {
    id: "guided_stories",
    slug: "guided_stories",
    name: "Oral History & Folklore",
    description: "Tales passed down by village elders, custodians & local chroniclers",
    icon: "📜",
    compatibleTravelTastes: ["historical", "culture_art", "local_life"],
  },
  {
    id: "coastal_walks",
    slug: "coastal_walks",
    name: "Wild Coastal Headlands",
    description: "Laterite sea cliffs, secret tidal inlets & fisherman tracks",
    icon: "🌊",
    compatibleTravelTastes: ["beaches", "nature", "photography"],
  },
  {
    id: "seafood",
    slug: "seafood",
    name: "Coastal & River Flavors",
    description: "Fresh estuary catches, claypot curries & harbor fish auctions",
    icon: "🐟",
    compatibleTravelTastes: ["food", "beaches", "local_life"],
  },
  {
    id: "street_food",
    slug: "street_food",
    name: "Street Feasts & Night Bazaars",
    description: "Steaming woks, regional snacks & lively evening stalls",
    icon: "🍢",
    compatibleTravelTastes: ["food", "nightlife"],
  },
  {
    id: "authentic_recipes",
    slug: "authentic_recipes",
    name: "Heirloom Hearth Cooking",
    description: "Traditional wood-fired cooking & seasonal organic ingredients",
    icon: "🍲",
    compatibleTravelTastes: ["food", "local_life"],
  },
  {
    id: "monastic_chants",
    slug: "monastic_chants",
    name: "Monastic Chants & Bells",
    description: "Resonant morning prayers, temple cymbals & spiritual calm",
    icon: "🔔",
    compatibleTravelTastes: ["spiritual", "mountains", "peaceful"],
  },
  {
    id: "sacred_rituals",
    slug: "sacred_rituals",
    name: "Sacred River Rituals",
    description: "Floating clay lamps, incense offerings & evening ghat ceremonies",
    icon: "✨",
    compatibleTravelTastes: ["spiritual", "historical", "nightlife"],
  },
  {
    id: "artisan_studios",
    slug: "artisan_studios",
    name: "Master Artisan Studios",
    description: "Watch weavers, bell-metal casters & potters at work",
    icon: "🔨",
    compatibleTravelTastes: ["culture_art", "local_life"],
  },
  {
    id: "folk_performances",
    slug: "folk_performances",
    name: "Folk Ballads & Music",
    description: "Acoustic storytelling, baul melodies & traditional strings",
    icon: "🪕",
    compatibleTravelTastes: ["culture_art", "local_life", "nightlife"],
  },
  {
    id: "village_homestays",
    slug: "village_homestays",
    name: "Village Homestay Living",
    description: "Living alongside host families, eating from backyard gardens",
    icon: "🏡",
    compatibleTravelTastes: ["local_life", "mountains", "nature"],
  },
  {
    id: "river_navigation",
    slug: "river_navigation",
    name: "Wooden Skiffs & Canoes",
    description: "Drifting down quiet river channels on handmade wooden craft",
    icon: "🛶",
    compatibleTravelTastes: ["adventure", "nature", "beaches"],
  },
  {
    id: "astro_sky",
    slug: "astro_sky",
    name: "Dark Sky Stargazing",
    description: "Zero light pollution, crystal-clear Milky Way & celestial views",
    icon: "🌌",
    compatibleTravelTastes: ["photography", "mountains", "nightlife", "nature"],
  },
  {
    id: "night_bazaars",
    slug: "night_bazaars",
    name: "Nocturnal Bazaars",
    description: "Bustling night markets, illuminated craft shops & midnight tea",
    icon: "🏮",
    compatibleTravelTastes: ["nightlife", "food", "local_life"],
  },
  {
    id: "ambient_music",
    slug: "ambient_music",
    name: "Acoustic Fire Evenings",
    description: "Campfire songs, desert folk rhythms & intimate starlit sessions",
    icon: "🔥",
    compatibleTravelTastes: ["nightlife", "culture_art", "adventure"],
  },
];
