import type { TravelTaste } from "../../types/taste";

export const TRAVEL_TASTES: TravelTaste[] = [
  {
    id: "mountains",
    slug: "mountains",
    name: "Mountains",
    description: "Peaks, alpine valleys, viewpoints & remote passes",
    icon: "🏔️",
    example: "Himalayan ridges, high mountain trails, valley homestays",
  },
  {
    id: "nature",
    slug: "nature",
    name: "Nature & Wildlife",
    description: "Old-growth groves, living root bridges & rich biodiversity",
    icon: "🌿",
    example: "Sacred forests, estuarine waterways, bird sanctuaries",
  },
  {
    id: "photography",
    slug: "photography",
    name: "Photography",
    description: "Vantage points, golden hour light & dramatic architectural frames",
    icon: "📸",
    example: "Ridge sunrise lookouts, starlit dunes, misty river reflections",
  },
  {
    id: "historical",
    slug: "historical",
    name: "Historical & Heritage",
    description: "Ancient stone carvings, stepwells & forgotten fortress ramparts",
    icon: "🏛️",
    example: "17th-century terracotta temples, subterranean stepwells, hill palaces",
  },
  {
    id: "beaches",
    slug: "beaches",
    name: "Beaches & Coasts",
    description: "Quiet fishing shores, sea cliffs & secluded estuarine coves",
    icon: "🏖️",
    example: "Red laterite headlands, natural springs, tranquil backwaters",
  },
  {
    id: "food",
    slug: "food",
    name: "Food & Culinary",
    description: "Secret kitchens, regional thalis & authentic heirloom recipes",
    icon: "🍜",
    example: "Claypot fish curries, tea estate tastings, tribal forest foraging",
  },
  {
    id: "spiritual",
    slug: "spiritual",
    name: "Spiritual & Sacred",
    description: "High-altitude gompas, river ghats & silent monastic sanctuaries",
    icon: "🪔",
    example: "Tibetan prayer dawn rituals, evening river aartis, meditation caves",
  },
  {
    id: "culture_art",
    slug: "culture_art",
    name: "Culture & Living Art",
    description: "Indigenous craft guilds, handlooms & living folklore traditions",
    icon: "🎨",
    example: "Dokra bell-metal casting, palm-leaf pattachitra, baul minstrels",
  },
  {
    id: "adventure",
    slug: "adventure",
    name: "Adventure & Trekking",
    description: "Rugged backcountry routes, river rapids & cliff traverses",
    icon: "🧗",
    example: "Gorge expeditions, cane bridge crossings, high passes over 4,500m",
  },
  {
    id: "local_life",
    slug: "local_life",
    name: "Local Life & Slow Travel",
    description: "Agrarian rhythms, artisan hamlets & authentic village hearths",
    icon: "🌾",
    example: "River island pottery colonies, seasonal orchard harvests, homestays",
  },
  {
    id: "sunrise_sunset",
    slug: "sunrise_sunset",
    name: "Sunrise & Sunset",
    description: "Dawn crests, twilight skies & dramatic panoramic horizons",
    icon: "🌅",
    example: "Kanchenjunga first light, desert sand twilight, misty dawn rowboats",
  },
  {
    id: "nightlife",
    slug: "nightlife",
    name: "Nightlife & Nocturnal",
    description: "Atmospheric night bazaars, riverside music & dark sky reserves",
    icon: "🌙",
    example: "Lantern-lit food alleys, starlit desert camps, acoustic fire gatherings",
  },
];
